DATE_FORMAT = "%d/%m/%Y"
TIME_FORMAT = "%H:%M"
DATETIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT
DATETIME_FULL = f"{DATETIME_FORMAT}:%S"

XLSX_DATETIME_FORMAT = "%d_%m_%Y_%H_%M_%S"
CONTENT_TYPE_XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
CONTENT_TYPE_XLS = "application/vnd.ms-excel"
CONTENT_TYPE_ZIP = "application/zip"
CONTENT_TYPE_MP3 = "audio/mpeg"

MENU_VENTAS = "1"
MENU_REPORTES = "2"
MENU_MANTENIMIENTOS = "3"

API_ACTION_HOME = "home"
API_ACTION_LIST = "list"
API_ACTION_ADD = "add"
API_ACTION_EDIT = "edit"
API_ACTION_DELETE = "delete"
API_ACTION_PARTIAL = "partial"
API_ACTION_EXPORT = "export"
API_ACTION_IMPORT = "import"
API_ACTION_READ = "read"
API_ACTION_RESET = "reset"
API_ACTION_HISTORY = "history"
API_ACTION_PARTIAL_PLUS = "partial_plus"
API_ACTION_PARTIAL_SEARCH = "partial_search"
API_ACTION_COMMENT = "comment"
API_ACTION_CANCEL_EDITOR = "cancel_editor"
API_ACTION_RELATED = "related"

API_ACTION_HOME_STR = "Ver"
API_ACTION_LIST_STR = "Ver"
API_ACTION_ADD_STR = "Añadir"
API_ACTION_EDIT_STR = "Editar"
API_ACTION_DELETE_STR = "Eliminar"
API_ACTION_PARTIAL_STR = "Ver"
API_ACTION_EXPORT_STR = "Exportar"
API_ACTION_IMPORT_STR = "Importar"
API_ACTION_READ_STR = "Ver"
API_ACTION_RESET_STR = "Resetear contraseña"
API_ACTION_HISTORY_STR = "Ver histórico"
API_ACTION_PARTIAL_PLUS_STR = "Ver"
API_ACTION_PARTIAL_SEARCH_STR = "Ver"
API_ACTION_COMMENT_STR = "Dejar comentario"
API_ACTION_CANCEL_EDITOR_STR = "Cancelar editor"
API_ACTION_RELATED_STR = "Ver elementos"

API_ACTION_MODAL_TITLE = {
    API_ACTION_HOME: API_ACTION_HOME_STR,
    API_ACTION_LIST: API_ACTION_LIST_STR,
    API_ACTION_ADD: API_ACTION_ADD_STR,
    API_ACTION_EDIT: API_ACTION_EDIT_STR,
    API_ACTION_DELETE: API_ACTION_DELETE_STR,
    API_ACTION_PARTIAL: API_ACTION_PARTIAL_STR,
    API_ACTION_EXPORT: API_ACTION_EXPORT_STR,
    API_ACTION_IMPORT: API_ACTION_IMPORT_STR,
    API_ACTION_READ: API_ACTION_READ_STR,
    API_ACTION_RESET: API_ACTION_RESET_STR,
    API_ACTION_HISTORY: API_ACTION_HISTORY_STR,
    API_ACTION_PARTIAL_PLUS: API_ACTION_PARTIAL_PLUS_STR,
    API_ACTION_PARTIAL_SEARCH: API_ACTION_PARTIAL_SEARCH_STR,
    API_ACTION_COMMENT: API_ACTION_COMMENT_STR,
    API_ACTION_CANCEL_EDITOR: API_ACTION_CANCEL_EDITOR_STR,
    API_ACTION_RELATED: API_ACTION_RELATED_STR,
}

TODOS_STR = "TODOS"
TODOS = ""

HISTORY_EDITOR = "Tramitador en curso"
HISTORY_EDITOR_CANCEL = "Tramitador en curso Cancelar"

ACCORDION_CSS_DISABLED = "bg-body-tertiary text-body-tertiary"
EMPTY_VALUE = "-"

DPTO_CODIGO_LIMA = "15"
DPTO_CODIGO_CALLAO = "07"

TRUE_STR = "SÍ"
FALSE_STR = "NO"

RELATED_TAG = "-related"
RELATED_NAME = "Related"
